"""Plain dataclasses used across the battle engine.

These have no side effects and no AppKit imports — every battle module
imports the relevant subset from here. Defining them up-front means the
TDD workflow for damage / engine / team_gen can red-test against real
types instead of dict shapes.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal


# Difficulty is a closed string set so callers can switch on it.
# Easy (1 mon, much weaker), Medium (2 mons, slightly weaker), Hard
# (3 mons, around player's level). Reward multipliers + level-deltas
# live in ``team_gen.py``.
Difficulty = Literal["easy", "medium", "hard"]

# Move category drives which (attack, defense) pair is used in the
# damage formula. Status moves deal no damage but may have effects in
# future expansions; for v1 they're inert.
MoveCategory = Literal["physical", "special", "status"]


@dataclass(frozen=True, slots=True)
class Move:
    """A battle move loaded from PokeAPI's ``/move/{name}/`` endpoint.

    ``power`` is None for status moves; ``accuracy`` is None for
    never-miss moves (Swift, Aerial Ace, …).
    """

    key: str                   # PokeAPI slug, e.g. "tackle"
    name: str                  # Display name, e.g. "Tackle"
    type: str                  # Lowercase type, e.g. "normal"
    category: MoveCategory
    power: int | None
    accuracy: int | None
    pp: int                    # Max PP — current PP tracked separately
    priority: int = 0          # Filtered out (only priority=0 in v1)
    description: str = ""      # Short effect text from PokeAPI (UI tooltip)


@dataclass(frozen=True, slots=True)
class BattleStats:
    """A snapshot of one Pokémon's combat-relevant stats.

    Built from ``pokemon.stats.final_stats(...)`` for player Pokémon and
    from the trainer-pokemon row for opponents. Immutable — turn
    resolution creates new instances rather than mutating in place.
    """

    species_dex_id: int
    level: int
    types: tuple[str, ...]
    hp_max: int
    hp_current: int
    attack: int
    defense: int
    sp_attack: int
    sp_defense: int
    speed: int
    moves: tuple[Move, ...]    # 1-4 moves available this battle
    move_pps: tuple[int, ...]  # current PP per slot, parallel to moves
    name: str = ""             # display label (nickname or species name)


@dataclass(frozen=True, slots=True)
class TrainerMon:
    """A trainer's Pokémon as generated by ``team_gen``. Translates to a
    BattleStats via the engine when it enters the battlefield."""

    species_dex_id: int
    level: int
    nature: str
    ivs: tuple[int, int, int, int, int, int]  # hp, atk, def, spa, spd, spe
    move_keys: tuple[str, ...]                # 1-4 move slugs


@dataclass(frozen=True, slots=True)
class DamageResult:
    """Result of one move's damage roll. ``effectiveness_label`` is the
    user-facing string ("It's super effective!", "It's not very
    effective…", "It had no effect.", or "")."""

    damage: int
    crit: bool
    effectiveness: float       # 0.0, 0.25, 0.5, 1.0, 2.0, 4.0
    effectiveness_label: str
    missed: bool = False


@dataclass(slots=True)
class TurnResult:
    """Outcome of resolving one player + opponent action.

    ``log`` is rendered to the battle pane's text feed. ``player_state``
    and ``opp_state`` are the post-turn snapshots; the caller writes
    them back to the battle's in-memory state. Faint flags let the
    caller decide between continuing, switching the trainer's next
    Pokémon, or ending the battle.
    """

    log: list[str] = field(default_factory=list)
    player_state: BattleStats | None = None
    opp_state: BattleStats | None = None
    player_fainted: bool = False
    opp_fainted: bool = False


@dataclass(frozen=True, slots=True)
class Rewards:
    """End-of-battle payout. ``xp_per_defeat`` is per-Pokémon so the
    UI can credit XP incrementally as opponents fall."""

    money: int
    xp_per_defeat: int
    item_drops: dict[str, int]
